export const copy = {
  en: {
    nav: ["Home", "About", "Career", "Projects", "Achievements", "Contact"],
    name: "Taras Shevchenko",
    role: "Full-Stack Engineer",
    location: "Based in Chernihiv, Ukraine",
    cv: "Download CV",
    rights: "All rights reserved.",
    skip: "Skip to main content",
    menu: "Toggle navigation",
    photo: "View profile photo",
    close: "Close photo",
    light: "Switch to light theme",
    dark: "Switch to dark theme",
    titles: [
      "Hi, I’m Taras Shevchenko",
      "About Me",
      "Career",
      "Projects",
      "Achievements",
      "Contact",
    ],
    descriptions: [
      "",
      "Learn more about my background, skills, and professional experience.",
      "My professional journey and work experience.",
      "A selection of things I’ve designed, developed, and delivered.",
      "A few milestones from my engineering journey.",
      "Have a project in mind? Let’s talk.",
    ],
    intro:
      "I build thoughtful web products, from responsive React interfaces to backend services, real-time data flows, and AI integrations. React, Next.js, TypeScript, and a focus on reliable delivery.",
    explore: "Explore my experience, the tools I use, and what I build.",
    aboutHeadline:
      "Full-Stack Engineer | React, Next.js & TypeScript | 7+ Years of Experience | Building reliable web products from interface to production.",
    about: [
      "I design and develop web products, from accessible, responsive user interfaces to backend services, APIs, and database-backed workflows. My experience spans CRM, fintech, e-commerce, blockchain, and geoportals.",
      "I’ve migrated production React applications to Next.js, built real-time interfaces and trading charts, and delivered server-side features with tRPC, NestJS, and PostgreSQL.",
      "I also integrate AI into product workflows, using the OpenAI API and locally deployed Qwen models. I take features from architecture through deployment and production support, with a focus on performance and maintainability.",
    ],
    regards: "Best regards,",
    skills: "Skills & Tools",
    skillsDescription: "Technologies and tools I use to bring ideas to life.",
    categories: {
      All: "All",
      Main: "Main",
      Frontend: "Frontend",
      Backend: "Backend",
      Database: "Database",
      Tools: "Tools",
    },
    projectsTitle: "Projects Showcase",
    projectsSubtitle: "Selected work and the stories behind it.",
    coming: "New projects are on the way",
    comingDescription:
      "I’m putting together a new selection of work. Check back soon for project details and live demos.",
    aboutSubtitle: "Who I am and what I do.",
    careerSubtitle: "My professional journey and experience.",
    achievementsSubtitle: "From frontend architecture to production delivery.",
    skillsSubtitle: "Frontend, backend, and the tools in between.",
    details: "Show details",
    hideDetails: "Hide details",
    viewProject: "View project",
    source: "Source code",
    contactTitle: "Let’s build something together.",
    contactText:
      "For opportunities, collaborations, or a conversation about your next web product, send me an email.",
    email: "Email me",
    copied: "Email copied",
    copyEmail: "Copy email address",
    copyError: "Couldn’t copy. Use the email link instead.",
    social: "Find me online",
    github: "Code, experiments, and open-source work.",
    linkedin: "Professional experience and connections.",
    milestones: [
      [
        "Modernizing production applications",
        "Migrated React applications to Next.js and established a maintainable frontend architecture.",
        "React · Next.js · Architecture",
      ],
      [
        "Making real-time data usable",
        "Built WebSocket interfaces, trading charts, and complex asynchronous data flows for fintech and e-commerce products.",
        "WebSockets · Redux-Saga · Trading charts",
      ],
      [
        "Taking features all the way to production",
        "Designed backend services, containerized applications, and automated checks, builds, and deployments.",
        "NestJS · PostgreSQL · Docker · CI/CD",
      ],
      [
        "Connecting AI to real product workflows",
        "Integrated OpenAI APIs and locally deployed Qwen models into assistants connected to market data and product workflows.",
        "OpenAI API · Qwen · AI integrations",
      ],
    ],
    missing: "Page not found",
    missingText:
      "This page isn’t here. You can return home or explore the sections in the menu.",
    back: "Back to home",
  },
  uk: {
    nav: [
      "Головна",
      "Про мене",
      "Кар’єра",
      "Проєкти",
      "Досягнення",
      "Контакти",
    ],
    name: "Тарас Шевченко",
    role: "Full-Stack Engineer",
    location: "Чернігів, Україна",
    cv: "Завантажити CV",
    rights: "Усі права захищено.",
    skip: "Перейти до вмісту",
    menu: "Відкрити або закрити меню",
    photo: "Переглянути фото",
    close: "Закрити фото",
    light: "Увімкнути світлу тему",
    dark: "Увімкнути темну тему",
    titles: [
      "Привіт, я Тарас Шевченко",
      "Про мене",
      "Кар’єра",
      "Проєкти",
      "Досягнення",
      "Контакти",
    ],
    descriptions: [
      "",
      "Мій досвід, навички та професійний шлях.",
      "Мій професійний шлях і досвід роботи.",
      "Добірка того, що я спроєктував, розробив і запустив.",
      "Кілька важливих результатів моєї роботи.",
      "Маєте ідею проєкту? Поговорімо.",
    ],
    intro:
      "Створюю продумані вебпродукти: від адаптивних React-інтерфейсів до серверних сервісів, даних у реальному часі та AI-інтеграцій. React, Next.js, TypeScript і увага до надійної роботи продукту.",
    explore: "Мій досвід, інструменти та продукти, які я створюю.",
    aboutHeadline:
      "Full-Stack Engineer | React, Next.js і TypeScript | Понад 7 років досвіду | Надійні вебпродукти від інтерфейсу до продакшену.",
    about: [
      "Проєктую та розробляю вебпродукти: від доступних адаптивних інтерфейсів до серверних сервісів, API та роботи з базами даних. Маю досвід у CRM, фінтеху, електронній комерції, блокчейні та геопорталах.",
      "Мігрував продакшен-застосунки з React на Next.js, створив інтерфейси реального часу й торгові графіки та реалізував серверну функціональність на tRPC, NestJS і PostgreSQL.",
      "Також інтегрую AI у продуктові процеси через OpenAI API та локально розгорнуті моделі Qwen. Веду функціональність від архітектури до розгортання й підтримки, приділяючи увагу продуктивності та підтримуваності коду.",
    ],
    regards: "З повагою,",
    skills: "Навички та інструменти",
    skillsDescription: "Технології та інструменти, з якими я втілюю ідеї.",
    categories: {
      All: "Усі",
      Main: "Основні",
      Frontend: "Фронтенд",
      Backend: "Бекенд",
      Database: "Бази даних",
      Tools: "Інструменти",
    },
    projectsTitle: "Мої проєкти",
    projectsSubtitle: "Вибрані роботи та історії їх створення.",
    coming: "Нові проєкти вже на підході",
    comingDescription:
      "Готую нову добірку робіт. Незабаром тут з’являться описи проєктів і посилання на демо.",
    aboutSubtitle: "Хто я і чим займаюся.",
    careerSubtitle: "Мій професійний шлях і досвід.",
    achievementsSubtitle: "Від архітектури фронтенду до продакшену.",
    skillsSubtitle: "Фронтенд, бекенд та інструменти розробки.",
    details: "Докладніше",
    hideDetails: "Згорнути",
    viewProject: "Переглянути",
    source: "Вихідний код",
    contactTitle: "Створімо щось разом.",
    contactText:
      "Напишіть мені щодо співпраці, професійних можливостей або вашого наступного вебпродукту.",
    email: "Написати листа",
    copied: "Email скопійовано",
    copyEmail: "Скопіювати email",
    copyError: "Не вдалося скопіювати. Скористайтеся посиланням на email.",
    social: "Я в мережі",
    github: "Код, експерименти та відкриті проєкти.",
    linkedin: "Професійний досвід і контакти.",
    milestones: [
      [
        "Модернізація продакшен-застосунків",
        "Мігрував React-застосунки на Next.js і впровадив підтримувану архітектуру фронтенду.",
        "React · Next.js · Архітектура",
      ],
      [
        "Зручна робота з даними реального часу",
        "Створив WebSocket-інтерфейси, торгові графіки й складні асинхронні потоки даних для фінтеху та електронної комерції.",
        "WebSockets · Redux-Saga · Торгові графіки",
      ],
      [
        "Від функціональності до продакшену",
        "Спроєктував серверні сервіси, контейнеризував застосунки й автоматизував перевірки, збірки та розгортання.",
        "NestJS · PostgreSQL · Docker · CI/CD",
      ],
      [
        "AI у реальних продуктових процесах",
        "Інтегрував OpenAI API та локальні моделі Qwen в асистентів, пов’язаних із ринковими даними та продуктовими процесами.",
        "OpenAI API · Qwen · AI-інтеграції",
      ],
    ],
    missing: "Сторінку не знайдено",
    missingText:
      "Такої сторінки немає. Поверніться на головну або виберіть розділ у меню.",
    back: "На головну",
  },
};
